name: 'Opex Dashboard Tool'
description: 'Used to create Dashboard'
inputs:
  command:
    description: 'command'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
branding:
  icon: 'git-commit'
  color: 'green'
