name: Reflection

on: push

jobs:
  reflect:
    permissions:
      contents: read
    name: Reflect
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run current action
        uses: ./
        with:
          template: azure-dashboard
          config: ./assets/examples/config.yaml
      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Apply
        run: |
          sed -i "s/$/MySubscription/g"                 azure-dashboard/env/dev/backend.ini
          sed -i "s/resource_group_name.*/& myrg/g"     azure-dashboard/env/dev/backend.tfvars
          sed -i "s/storage_group_name.*/& mystorage/g" azure-dashboard/env/dev/backend.tfvars
          sed -i "s/container_name.*/& mycontainer/g"   azure-dashboard/env/dev/backend.tfvars
          sed -i "s/key.*/& mykey/g"                    azure-dashboard/env/dev/backend.tfvars
          sed -i "s/prefix.*/& pagopa/g"                azure-dashboard/env/dev/terraform.tfvars
          sed -i "s/env_short.*/& d/g"                  azure-dashboard/env/dev/terraform.tfvars
          # ./terraform.sh init dev
          # ./terraform.sh apply dev -auto-approve
      - name: List all current files
        run: |
          pwd
          ls -R
          cat \
            azure-dashboard/env/dev/backend.ini
            azure-dashboard/env/dev/backend.tfvars
            azure-dashboard/env/dev/terraform.tfvars

